### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by BDQ** [incandescent/session-injector#4]
First, thank you for this project it's a real time saver.

Any chance you could do another gem release including the Rails 3.2 fix recently?

**Comment by cwise** [comment]
+1

**Comment by marckohlbrugge** [comment]
+2

**Comment by curbsaleem** [comment]
+3

gems/session_injector-0.0.1/lib/session_injector.rb:44:in `initialize': uninitialized constant ActiveSupport::SecureRandom (NameError)
